kind: ConfigMap
apiVersion: v1
metadata:
  name: cluster-config
  namespace: {{ .Values.global.namespace }}
  annotations: {{ include "global.annotations.standard" . | indent 4 }}
data:
  name: {{ .Values.config.name }}
